luxteam/cis_tools

- close_RDP.bat
* JIRA TICKET
* https://adc.luxoft.com/jira/browse/STVCIS-753
* PURPOSE
* Allow to use close_RDP.bat on vm
> Improve close_rdp.bat

- runJenkinsAgent.bat
PURPOSE
* Update jenkins agent on agent starts
> Add downloading agent to runJenkinsAgent.bat

- receiveFilesCoreConf.bat
* JIRA TICKET:
* https://adc.luxoft.com/jira/browse/STVCIS-1085
* PURPOSE
* Add total count feature for Core.
* EFFECT OF CHANGE
* Add script for download json files with core scenes configuration.
* TECHNICAL STEPS
* None
* NOTES FOR REVIEWERS
* PRs in other repositories:
* rpr_pipelines: https://github.com/luxteam/rpr_pipelines/pull/183
* jobs_test_core: https://github.com/luxteam/jobs_test_core/pull/14
* jobs_launcher: https://github.com/luxteam/jobs_launcher/pull/46
* REPORTS
* Blender: https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/1795/Test_20Report/
* Maya: https://rpr.cis.luxoft.com/job/RadeonProRenderMayaPluginManual/3125/Test_20Report/
* Max: https://rpr.cis.luxoft.com/job/RadeonProRenderMaxPluginManual/858/Test_20Report/
* Core: …
> Add total count feature for Core

- install.bat
- receiveFilesCoreConf.bat
- receiveFilesSync.bat
- sendFiles.bat
* None
* Replace single quotes by double quotes
* https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/2691/
> Replace single quotes by double quotes

- houdini_api.py
- installHoudiniLinux.sh
- installHoudiniOSX.sh
* https://adc.luxoft.com/jira/browse/STVCIS-1721
* Add from machines scripts for install houdini
* OSX: https://rpr.cis.luxoft.com/job/RadeonProRenderUSDPluginManual/391/
* Ubuntu: https://rpr.cis.luxoft.com/job/RadeonProRenderUSDPluginManual/392/
* CentOS: https://rpr.cis.luxoft.com/job/RadeonProRenderUSDPluginManual/394/
> Add from machines scripts for install houdini

- installHoudiniOSX.sh
* https://adc.luxoft.com/jira/browse/STVCIS-1721
* Remove sudo from installHoudiniOSX script
* OSX: https://rpr.cis.luxoft.com/job/RadeonProRenderUSDPluginManual/391
> Remove sudo from installHoudiniOSX script

- houdini_api.py
* None
* Add possibility to set Houdini location through env vars
* rpr_pipelines: https://github.com/luxteam/rpr_pipelines/pull/402
* https://rpr.cis.luxoft.com/job/RadeonProRenderUSDPluginManual/413/
> Add possibility to set Houdini location through env vars

- houdini_api.py
* https://adc.luxoft.com/jira/browse/STVCIS-1713
* Rename macosx to macos
* https://rpr.cis.luxoft.com/job/RadeonProRenderUSDPluginManual/453/Test_20Report/
> Fix MacOS platform

- receiveFiles.bat
- receiveFiles.sh
- receiveFilesCoreConf.bat
- receiveFilesSync.bat
- receiveFilesSync.sh
- sendFiles.bat
- sendFiles.sh
* https://adc.luxoft.com/jira/browse/STVCIS-1710
* Pass REMOTE_HOST as a param of scripts
* **THIS PR SHOULD BE MERGED ONLY AFTER MOVING OF BUILDS SERVICE**
* rpr_pipelines: https://github.com/luxteam/rpr_pipelines/pull/372
* https://rpr.cis.luxoft.com/job/RadeonProRenderCoreManual/865/
> Pass REMOTE_HOST as a param of scripts

- auth_github.py
* Implement script for auth github installation
> Implement script for auth github installation

- auth_github.py
* Pass organization_name as a param and private_ket through env vars in auth_github script
> Pass organization_name as a param and private_ket through env vars in auth_github script

- auth_github.py
* Import install function in auth_github script
> Import install function in auth_github script

- auth_github.py
* Add install function in auth_github script
> Add install function in auth_github script

- auth_github.py
* Fix imports in auth_github script
> Fix imports in auth_github script

- auth_github.py
* Fix auth_github script for Unix machines
> Fix auth_github script for Unix machines

- stash.bat
- stash.sh
- stashDebug.bat
- stashDebug.sh
- unstash.bat
- unstash.sh
- unstashDebug.bat
- unstashDebug.sh
* Add functions for statsh/unstash
> Add functions for statsh/unstash

- stash.bat
- stash.sh
- stashDebug.bat
- stashDebug.sh
- unstash.bat
- unstash.sh
- unstashDebug.bat
- unstashDebug.sh
* Fix keys of command in stash/unstash scripts
> Fix keys of command in stash/unstash scripts

- unstash.bat
- unstash.sh
> Fix keys of unstash scripts

- removeStashes.bat
- removeStashes.sh
- unstash.bat
- unstashDebug.bat
- unstashDebug.sh
* Move deleting of stashes to separate scripts
> Move deleting of stashes to separate scripts

- stash.bat
- stash.sh
- stashDebug.bat
- stashDebug.sh
- unstash.bat
- unstash.sh
- unstashDebug.bat
- unstashDebug.sh
* Update stash functions + remove debug stash functions
> Update stash functions + remove debug stash functions

- downloadFilesSync.bat
- downloadFilesSync.sh
* https://adc.luxoft.com/jira/browse/STVCIS-2120
* Add custom keys param for upload and download scripts
>  Add custom keys param for download files sync scripts

- downloadFiles.bat
- downloadFilesSync.bat
- downloadFilesSync.sh
* https://adc.luxoft.com/jira/browse/STVCIS-2142
* Download symlinks
> Download symlinks

- auth_github.py
* https://adc.luxoft.com/jira/browse/STVCIS-2158
* Check should token be decoded or not
> Check should token be decoded or not

- make_redirect_page.bat
- make_redirect_page.py
- make_redirect_page.sh
- templates/redirect_report_page.html
- unzipFile.bat
- unzipFile.sh
* https://adc.luxoft.com/jira/browse/STVCIS-2173
* Add unzip and make_redirect_link scripts
> Add unzip and make_redirect_link scripts

- make_redirect_page.bat
- make_redirect_page.sh
- unzipFile.sh
* https://adc.luxoft.com/jira/browse/STVCIS-2173
* Stabilized unzipFile.sh and make_redirect_page scripts
> Stabilized unzipFile.sh and make_redirect_page scripts

- downloadFiles.bat
- unzipFile.bat
- uploadFiles.bat
* https://adc.luxoft.com/jira/browse/STVCIS-2166
* Update downloadFiles, unzipFile and uploadFiles script to use them with stashes with spaces in name
* https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/4492/
> Update downloadFiles, unzipFile and uploadFiles script to use them with stashes with spaces in name

- unzipFile.sh
- uploadFiles.sh
* https://adc.luxoft.com/jira/browse/STVCIS-2166
* Small updates for use uploadFiles and unzipFile scripts with stashes
* https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/4506/
> Small updates for use uploadFiles and unzipFile scripts with stashes

- unzipFile.bat
- unzipFile.sh
* https://adc.luxoft.com/jira/browse/STVCIS-2166
* Replace files if call unzip scripts
> Replace files if call unzip scripts

- check_builds_existence.py
* https://adc.luxoft.com/jira/browse/STVCIS-2173
* Implement script to clear content of builds which were deleted on Jenkins
* rpr_pipelines: https://github.com/luxteam/rpr_pipelines/pull/564
> Implement script to clear content of builds which were deleted on Jenkins
